"use client";

import { useActionState, useState } from "react";
import { ArrowDown, ArrowUp } from "lucide-react";
import { deleteRuleAction, moveRuleAction, saveRuleAction, toggleRuleAction } from "@/lib/actions/rules";
import { saveAutomationAction } from "@/lib/actions/settings";
import { AUTO_REPLY_AUDIENCES, AUTO_REPLY_TRIGGERS, WEEKDAYS, labelFor, weekdayLabel } from "@/lib/constants";
import type { Settings, Template } from "@/lib/db/schema";
import { formatDateTime, toDateTimeLocal } from "@/lib/format";
import { stageLabel } from "@/lib/pipeline";
import { useStages } from "@/components/pipeline/stages-provider";
import type { RuleWithTemplate } from "@/lib/queries/templates";
import type { ActionResult } from "@/lib/validation";
import { ConfirmButton, SubmitButton } from "@/components/ui/form-controls";
import { ChannelTag, EmptyState, Field, cx } from "@/components/ui/primitives";

export function AutomationToggles({ settings }: { settings: Settings }) {
  const [state, action] = useActionState<ActionResult<{ saved: boolean }>, FormData>(saveAutomationAction, { ok: true });
  return (
    <form action={action} className="panel">
      <div className="panel-header">
        <h2 className="panel-title">Master switches</h2>
        {state.ok && state.data?.saved ? <span className="text-[12px] text-sage-800">Saved</span> : null}
      </div>
      <div className="panel-body space-y-3">
        <label className="flex cursor-pointer items-start gap-3 text-[13px]">
          <input type="checkbox" name="emailAutoRepliesEnabled" defaultChecked={settings.emailAutoRepliesEnabled} className="checkbox mt-0.5" />
          <span>
            <span className="font-medium text-ink">Send automatic email replies</span>
            <span className="block text-ink-muted">When off, no email rule fires regardless of its own setting.</span>
          </span>
        </label>
        <label className="flex cursor-pointer items-start gap-3 text-[13px]">
          <input type="checkbox" name="whatsappAutoRepliesEnabled" defaultChecked={settings.whatsappAutoRepliesEnabled} className="checkbox mt-0.5" />
          <span>
            <span className="font-medium text-ink">Send automatic WhatsApp replies</span>
            <span className="block text-ink-muted">Replies are sent within the 24-hour window that opens when a contact messages you.</span>
          </span>
        </label>
        <p className="text-[12px] text-ink-faint">Automatic replies only ever use your templates. Nothing is generated by AI. Bounces, newsletters and automated senders never receive a reply.</p>
        <SubmitButton variant="btn-secondary">Save switches</SubmitButton>
      </div>
    </form>
  );
}

function RuleForm({ rule, templates, timezone, onClose }: { rule: RuleWithTemplate | null; templates: Template[]; timezone: string; onClose: () => void }) {
  const stages = useStages();
  const [state, action] = useActionState<ActionResult<{ saved: boolean }>, FormData>(
    async (previous, formData) => {
      const result = await saveRuleAction(previous, formData);
      if (result.ok && result.data?.saved) onClose();
      return result;
    },
    { ok: true },
  );
  const [channel, setChannel] = useState<"email" | "whatsapp">((rule?.channel as "email" | "whatsapp") ?? "email");
  const [trigger, setTrigger] = useState(rule?.triggerType ?? "any");
  const errors = (!state.ok && state.fieldErrors) || {};
  const channelTemplates = templates.filter((t) => t.channel === "any" || t.channel === channel);

  return (
    <form action={action} className="space-y-4 rounded-md border border-sage-200 bg-sage-50/60 p-4">
      {rule ? <input type="hidden" name="id" value={rule.id} /> : null}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <Field label="Rule name" htmlFor="rule-name" error={errors.name}>
          <input id="rule-name" name="name" defaultValue={rule?.name ?? ""} className={cx("input", errors.name && "input-error")} autoFocus placeholder="Acknowledge new enquiries" />
        </Field>
        <Field label="Channel" htmlFor="rule-channel">
          <select id="rule-channel" name="channel" className="select" value={channel} onChange={(e) => setChannel(e.target.value as "email" | "whatsapp")}>
            <option value="email">Email</option>
            <option value="whatsapp">WhatsApp</option>
          </select>
        </Field>
        <Field label="Trigger" htmlFor="rule-trigger" hint={AUTO_REPLY_TRIGGERS.find((t) => t.key === trigger)?.description}>
          <select id="rule-trigger" name="triggerType" className="select" value={trigger} onChange={(e) => setTrigger(e.target.value)}>
            {AUTO_REPLY_TRIGGERS.map((t) => (
              <option key={t.key} value={t.key}>
                {t.label}
              </option>
            ))}
          </select>
        </Field>
        <Field label="Applies to" htmlFor="rule-audience">
          <select id="rule-audience" name="applyTo" className="select" defaultValue={rule?.applyTo ?? "all"}>
            {AUTO_REPLY_AUDIENCES.map((a) => (
              <option key={a.key} value={a.key}>
                {a.label}
              </option>
            ))}
          </select>
        </Field>
        {trigger === "weekly" ? (
          <>
            <div className="grid grid-cols-2 gap-2">
              <Field label="From" htmlFor="rule-weekly-from-day" error={errors.weeklyFromDay}>
                <select id="rule-weekly-from-day" name="weeklyFromDay" className="select" defaultValue={rule?.weekly?.fromDay ?? 5}>
                  {WEEKDAYS.map((d) => (
                    <option key={d.value} value={d.value}>
                      {d.label}
                    </option>
                  ))}
                </select>
              </Field>
              <Field label="At" htmlFor="rule-weekly-from-time" error={errors.weeklyFromTime}>
                <input id="rule-weekly-from-time" name="weeklyFromTime" type="time" defaultValue={rule?.weekly?.fromTime ?? "17:00"} className={cx("input", errors.weeklyFromTime && "input-error")} />
              </Field>
            </div>
            <div className="grid grid-cols-2 gap-2">
              <Field label="Until" htmlFor="rule-weekly-until-day" error={errors.weeklyUntilDay}>
                <select id="rule-weekly-until-day" name="weeklyUntilDay" className="select" defaultValue={rule?.weekly?.untilDay ?? 1}>
                  {WEEKDAYS.map((d) => (
                    <option key={d.value} value={d.value}>
                      {d.label}
                    </option>
                  ))}
                </select>
              </Field>
              <Field label="At" htmlFor="rule-weekly-until-time" error={errors.weeklyUntilTime} hint="Repeats every week, in your Settings time zone. The window may run past Sunday into the next week.">
                <input id="rule-weekly-until-time" name="weeklyUntilTime" type="time" defaultValue={rule?.weekly?.untilTime ?? "08:00"} className={cx("input", errors.weeklyUntilTime && "input-error")} />
              </Field>
            </div>
          </>
        ) : null}
        {trigger === "away" ? (
          <>
            <Field label="Away from" htmlFor="rule-away-from" error={errors.awayFrom}>
              <input id="rule-away-from" name="awayFrom" type="datetime-local" defaultValue={toDateTimeLocal(rule?.awayFrom, timezone)} className={cx("input", errors.awayFrom && "input-error")} />
            </Field>
            <Field label="Back on" htmlFor="rule-away-until" error={errors.awayUntil} hint="Messages arriving between these times get the reply. Times are in your Settings time zone.">
              <input id="rule-away-until" name="awayUntil" type="datetime-local" defaultValue={toDateTimeLocal(rule?.awayUntil, timezone)} className={cx("input", errors.awayUntil && "input-error")} />
            </Field>
          </>
        ) : null}
        {trigger === "keyword" ? (
          <Field label="Keywords" htmlFor="rule-keywords" className="md:col-span-2" error={errors.keywords} hint="One per line or comma separated. Matched anywhere in the subject or message, ignoring case.">
            <textarea id="rule-keywords" name="keywords" defaultValue={(rule?.keywords ?? []).join("\n")} className={cx("textarea min-h-20", errors.keywords && "input-error")} />
          </Field>
        ) : null}
        <Field label="Reply with template" htmlFor="rule-template" error={errors.templateId}>
          <select id="rule-template" name="templateId" className={cx("select", errors.templateId && "input-error")} defaultValue={rule?.templateId ?? ""}>
            <option value="">Choose a template</option>
            {channelTemplates.map((t) => (
              <option key={t.id} value={t.id}>
                {t.name}
              </option>
            ))}
          </select>
        </Field>
        <Field label="Cooldown (hours)" htmlFor="rule-cooldown" error={errors.cooldownHours} hint="Do not reply to the same contact again within this period.">
          <input id="rule-cooldown" name="cooldownHours" inputMode="numeric" defaultValue={rule?.cooldownHours ?? 24} className={cx("input", errors.cooldownHours && "input-error")} />
        </Field>
        <div className="md:col-span-2">
          <span className="label">Only for clients in these stages</span>
          <div className="flex flex-wrap gap-2">
            {stages.map((stage) => (
              <label key={stage.key} className="flex h-8 cursor-pointer items-center gap-2 rounded-sm border border-line-strong bg-paper px-2.5 text-[12px]">
                <input type="checkbox" name="stages" value={stage.key} defaultChecked={rule?.stages.includes(stage.key) ?? false} className="checkbox" />
                {stage.label}
              </label>
            ))}
          </div>
          <p className="mt-1.5 text-[12px] text-ink-faint">Leave all unticked to apply to every stage. Unknown contacts have no stage and only match when nothing is ticked.</p>
        </div>
        <label className="flex cursor-pointer items-center gap-2 text-[13px]">
          <input type="checkbox" name="enabled" defaultChecked={rule?.enabled ?? true} className="checkbox" />
          Rule enabled
        </label>
        {channel === "email" ? (
          <label className="flex cursor-pointer items-center gap-2 text-[13px]">
            <input type="checkbox" name="oncePerThread" defaultChecked={rule?.oncePerThread ?? true} className="checkbox" />
            Reply at most once per email conversation
          </label>
        ) : null}
      </div>
      {!state.ok && state.error ? <p className="form-error">{state.error}</p> : null}
      <div className="flex items-center gap-2">
        <SubmitButton>{rule ? "Save rule" : "Create rule"}</SubmitButton>
        <button type="button" className="btn btn-ghost" onClick={onClose}>
          Cancel
        </button>
      </div>
    </form>
  );
}

function AwayBadge({ state }: { state: RuleWithTemplate["awayState"] }) {
  if (state === "missing") return <span className="badge badge-neutral">Dates missing</span>;
  if (state === "scheduled") return <span className="badge badge-neutral">Scheduled</span>;
  if (state === "ended") return <span className="badge badge-neutral">Ended</span>;
  if (state === "active") return <span className="badge bg-sage-100 text-sage-900">Away now</span>;
  return null;
}

export function RuleEditor({ rules, templates, timezone }: { rules: RuleWithTemplate[]; templates: Template[]; timezone: string }) {
  const stages = useStages();
  const [editing, setEditing] = useState<string | "new" | null>(null);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-4">
        <p className="text-[13px] text-ink-muted">Rules are checked in order for every incoming message; the first matching rule sends its template and no other rule fires.</p>
        {editing !== "new" ? (
          <button type="button" className="btn btn-primary" onClick={() => setEditing("new")} disabled={templates.length === 0}>
            New rule
          </button>
        ) : null}
      </div>
      {templates.length === 0 ? <p className="form-error">Create a template first. Rules reply using your templates.</p> : null}
      {editing === "new" ? <RuleForm rule={null} templates={templates} timezone={timezone} onClose={() => setEditing(null)} /> : null}
      <div className="panel">
        {rules.length === 0 && editing !== "new" ? (
          <EmptyState title="No rules yet" description="Add a rule such as: reply to the first email from a new contact with your enquiry acknowledgement template." />
        ) : (
          <ol className="divide-y divide-line">
            {rules.map((rule, index) => (
              <li key={rule.id} className="px-5 py-4">
                {editing === rule.id ? (
                  <RuleForm rule={rule} templates={templates} timezone={timezone} onClose={() => setEditing(null)} />
                ) : (
                  <div className="flex items-start gap-4">
                    <div className="flex flex-col gap-1 pt-0.5">
                      <form action={moveRuleAction.bind(null, rule.id, "up")}>
                        <button type="submit" className="text-ink-faint hover:text-ink disabled:opacity-30" disabled={index === 0} aria-label="Move up">
                          <ArrowUp size={14} />
                        </button>
                      </form>
                      <form action={moveRuleAction.bind(null, rule.id, "down")}>
                        <button type="submit" className="text-ink-faint hover:text-ink disabled:opacity-30" disabled={index === rules.length - 1} aria-label="Move down">
                          <ArrowDown size={14} />
                        </button>
                      </form>
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <h3 className={cx("text-[14px] font-semibold", rule.enabled ? "text-ink" : "text-ink-muted line-through")}>{rule.name}</h3>
                        <ChannelTag channel={rule.channel} />
                        {!rule.enabled ? <span className="badge badge-neutral">Paused</span> : null}
                        {rule.enabled && rule.triggerType === "away" ? <AwayBadge state={rule.awayState} /> : null}
                      </div>
                      <p className="mt-1 text-[13px] text-ink-muted">
                        {labelFor(AUTO_REPLY_TRIGGERS, rule.triggerType)}
                        {rule.triggerType === "keyword" && rule.keywords.length > 0 ? ` (${rule.keywords.join(", ")})` : ""}
                        {rule.triggerType === "weekly" && rule.weekly ? ` (${weekdayLabel(rule.weekly.fromDay, true)} ${rule.weekly.fromTime} to ${weekdayLabel(rule.weekly.untilDay, true)} ${rule.weekly.untilTime})` : ""}
                        {rule.triggerType === "away" && rule.awayFrom && rule.awayUntil ? ` (${formatDateTime(rule.awayFrom, timezone)} to ${formatDateTime(rule.awayUntil, timezone)})` : ""} · {labelFor(AUTO_REPLY_AUDIENCES, rule.applyTo)}
                        {rule.stages.length > 0 ? ` · Stages: ${rule.stages.map((key) => stageLabel(stages, key)).join(", ")}` : ""}
                      </p>
                      <p className="mt-0.5 text-[12px] text-ink-faint">
                        Template: {rule.template?.name ?? "Missing"} · Cooldown {rule.cooldownHours}h
                        {rule.channel === "email" && rule.oncePerThread ? " · Once per conversation" : ""} · Sent {rule.timesTriggered} time{rule.timesTriggered === 1 ? "" : "s"}
                        {rule.lastTriggeredAt ? `, last ${formatDateTime(rule.lastTriggeredAt, timezone)}` : ""}
                      </p>
                    </div>
                    <div className="flex shrink-0 items-center gap-2">
                      <form action={toggleRuleAction.bind(null, rule.id, !rule.enabled)}>
                        <button type="submit" className="btn btn-secondary btn-sm">
                          {rule.enabled ? "Pause" : "Resume"}
                        </button>
                      </form>
                      <button type="button" className="btn btn-secondary btn-sm" onClick={() => setEditing(rule.id)}>
                        Edit
                      </button>
                      <ConfirmButton className="btn-ghost btn-sm" confirmText={`Delete the rule "${rule.name}"?`} action={() => deleteRuleAction(rule.id)}>
                        Delete
                      </ConfirmButton>
                    </div>
                  </div>
                )}
              </li>
            ))}
          </ol>
        )}
      </div>
    </div>
  );
}
